### ISSUE TITLE
ebpf的用途

### ISSUE THREAD

**Issue by fordream11** [nevermosby/linux-bpf-learning#11]
大佬你好，我想在内核网络IO路径上对指定的数据结构（msghdr/iov_iter/iovec）做可靠性加固（假设是极端环境、软硬件不可靠的场景）。比如说在内核访问这些数据结构前需要验证下这些数据结构的正确性，是否可以用ebpf程序对这些数据结构做监测，一旦内核访问这些数据结构，就跳转到我的ebpf程序执行？望百忙中抽空指导下实现思路，不胜感激~
PS：不知道有没有群/微信可以加一下呢？想交流学习下

**Comment by fordream11** [comment]
感谢大佬指导，现在还在抽时间去看ebpf的那本书。从发网络包的角度看，我关注的这些数据结构都是在TCP层处理之前或处理时的数据结构，所以暂时不确定是否具有可行性；另外kprobe是否能完成这个任务呢？

**Comment by nevermosby** [comment]
我理解，kprobe或者其他函数追踪hook能否满足你的需要，主要取决于在这个hook上能否访问到目标数据结构。

**Comment by fordream11** [comment]
好的，感谢指点！
