### ISSUE TITLE
ip link set dev 加载在内核出现问题

### ISSUE THREAD

**Issue by maquess** [nevermosby/linux-bpf-learning#5]
你好 clang完.c没有问题，但是加载内核的时候出现12 bytes struct bpf_elf_map fixup performed due to size mismatch!
ELF contains relo data for non ld64 instruction at offset 19! Compiler bug?!
 - Try to annotate functions with always_inline attribute!
Error fetching program/map!
是什么情况呢

**Comment by nevermosby** [comment]
@maquess 你好，请问具体是运行哪个demo代码？系统环境是怎样的？内核版本？

**Comment by maquess** [comment]
> 是运行哪个demo代码？系统环境是怎样的？内核版本

运行的linux-bpf-learning/bpf/bpf-maps/examples-in-kernel/xdp_ip_tracker_kern.c，正常clang编译完成之后，加载在网卡上出现的错误，系统环境是linux，版本是Linux ubuntu 4.15.0-29-generic #31-Ubuntu SMP UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by maquess** [comment]
> 

- [ ] 

> @maquess 你好，请问具体是运行哪个demo代码？系统环境是怎样的？内核版本？

运行的linux-bpf-learning/bpf/bpf-maps/examples-in-kernel/xdp_ip_tracker_kern.c，正常clang编译完成之后，加载在网卡上出现的错误，系统环境是linux，版本是Linux ubuntu 4.15.0-29-generic #31-Ubuntu SMP UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
